# Generated by Django 3.2.9 on 2021-11-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
