# Generated by Django 3.2.9 on 2021-11-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=100, verbose_name='Описание')),
                ('published_at', models.DateField(auto_now_add=True)),
                ('content', models.CharField(max_length=128, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ('-published_at',),
            },
        ),
    ]
